import { MemberHealthProfile } from '@/types/health';

export const PARENT_HEALTH_PROFILES: Record<string, MemberHealthProfile> = {
  mom: {
    memberId: 'mom',
    memberName: '妈妈',
    lastExamDate: '2024-04-18',
    metrics: [
      {
        id: 'mom-w',
        name: '体重',
        category: '基础体态',
        value: 63.5,
        unit: 'kg',
        normalRange: '50.0 ~ 58.0',
        status: 'attention',
        meaning: '略偏重，给膝关节及睡眠呼吸带来一定负荷',
        advice: '建议每餐七分饱，适度减少精制米面，有利于睡眠气道畅通。',
        trend: 'down',
      },
      {
        id: 'mom-bmi',
        name: '体质指数 (BMI)',
        category: '基础体态',
        value: 24.8,
        unit: 'kg/m²',
        normalRange: '18.5 ~ 23.9',
        status: 'attention',
        meaning: '超重边缘（标准上限为 23.9）',
        advice: '体重减轻 2~3 公斤可以明显改善打鼾程度。',
        trend: 'down',
      },
      {
        id: 'mom-bp-sys',
        name: '收缩压 (高压)',
        category: '心血管与血压',
        value: 126,
        unit: 'mmHg',
        normalRange: '90 ~ 130',
        status: 'normal',
        meaning: '指标非常理想，血管张力稳定',
        advice: '继续保持平稳心态与规律作息。',
        trend: 'stable',
      },
      {
        id: 'mom-bp-dia',
        name: '舒张压 (低压)',
        category: '心血管与血压',
        value: 78,
        unit: 'mmHg',
        normalRange: '60 ~ 85',
        status: 'normal',
        meaning: '处于黄金健康范围',
        advice: '早晚测量如无明显波动即十分安全。',
        trend: 'stable',
      },
      {
        id: 'mom-glu',
        name: '空腹血糖',
        category: '血糖代谢',
        value: 5.3,
        unit: 'mmol/L',
        normalRange: '3.9 ~ 6.1',
        status: 'normal',
        meaning: '糖代谢平稳正常，胰岛素功能好',
        advice: '少喝含糖饮料与甜点，继续保持粗细粮搭配。',
        trend: 'stable',
      },
      {
        id: 'mom-hba1c',
        name: '糖化血红蛋白',
        category: '血糖代谢',
        value: 5.4,
        unit: '%',
        normalRange: '4.0 ~ 6.0',
        status: 'normal',
        meaning: '近3个月的综合血糖状态优秀',
        advice: '每年体检定期复查一次即可。',
        trend: 'stable',
      },
      {
        id: 'mom-tc',
        name: '总胆固醇 (TC)',
        category: '血脂四项',
        value: 5.58,
        unit: 'mmol/L',
        normalRange: '2.80 ~ 5.18',
        status: 'attention',
        meaning: '轻度偏高，需警惕血液粘稠与血管硬化',
        advice: '炒菜多用橄榄油或菜籽油，少吃动物内脏和高油肥肉。',
        trend: 'up',
      },
      {
        id: 'mom-ldl',
        name: '低密度脂蛋白 (LDL-C)',
        category: '血脂四项',
        value: 3.42,
        unit: 'mmol/L',
        normalRange: '< 2.60',
        status: 'danger',
        meaning: '偏高！这是血管形成动脉粥样硬化斑块的核心指标',
        advice: '重点关注项：建议就诊咨询医生是否需补充小剂量他汀调脂。',
        trend: 'up',
      },
      {
        id: 'mom-hdl',
        name: '高密度脂蛋白 (HDL-C)',
        category: '血脂四项',
        value: 1.35,
        unit: 'mmol/L',
        normalRange: '> 1.04',
        status: 'normal',
        meaning: '“血管清道夫”指标达标，有益于血管保护',
        advice: '多做有氧散步可帮助维持高水平。',
        trend: 'stable',
      },
      {
        id: 'mom-tg',
        name: '甘油三酯 (TG)',
        category: '血脂四项',
        value: 1.68,
        unit: 'mmol/L',
        normalRange: '0.56 ~ 1.70',
        status: 'normal',
        meaning: '在正常参考值安全线内',
        advice: '晚上睡前 2 小时不要进食加餐。',
        trend: 'stable',
      },
      {
        id: 'mom-ua',
        name: '血尿酸 (UA)',
        category: '肝肾与痛风',
        value: 310,
        unit: 'μmol/L',
        normalRange: '150 ~ 360',
        status: 'normal',
        meaning: '尿酸水平正常，无痛风及高尿酸风险',
        advice: '日常多喝白开水促进肾脏代谢。',
        trend: 'stable',
      },
      {
        id: 'mom-cpap-ahi',
        name: '呼吸暂停指数 (AHI)',
        category: '专科特检',
        value: 0.9,
        unit: '次/小时',
        normalRange: '< 5.0',
        status: 'normal',
        meaning: '戴呼吸机后整夜无缺氧憋气，疗效极佳！',
        advice: '只要坚持佩戴，心脑血管缺氧风险就会彻底降至最低。',
        trend: 'down',
      },
    ],
    visitGuide: {
      recommendedDept: '心血管内科 / 睡眠医学科（呼吸内科）',
      reason: '低密度脂蛋白（LDL-C 3.42）偏高，需评估心血管防斑块方案；随访睡眠呼吸机疗效。',
      checklist: [
        '医保卡 & 身份证件',
        '近半年体检化验单原件（血脂四项报告）',
        '手机中近 1 个月的呼吸机打卡使用天数与 AHI 记录',
        '目前家中日常吃的所有药盒（包括钙片、维生素等）',
      ],
      questionsToDoctor: [
        '1. “医生，我最近体检低密度脂蛋白是 3.42，平时饮食挺清淡的，您看我需要吃小剂量的调脂药（如他汀）吗？”',
        '2. “我晚上睡觉一直在用呼吸机，每天能戴 6 小时以上，AHI 基本在 1 左右，机器压力（8.4）需要做复查或微调吗？”',
        '3. “请问需要给我开一个颈动脉彩超单子，看看血管里有没有斑块吗？”',
      ],
      lifestyleAdvice: [
        '食用油尽量换成单不饱和脂肪酸（橄榄油、茶油），每餐控制用油量。',
        '每天晚上睡前清洗湿化罐换纯净水，佩戴鼻罩时确认边缘无吹眼睛的漏气。',
        '每天傍晚饭后快走散步 30 分钟，持之以恒，有助降低坏胆固醇。',
      ],
      nextReviewDate: '2024-10-20 (建议半年复查血脂四项)',
    },
  },
  dad: {
    memberId: 'dad',
    memberName: '爸爸',
    lastExamDate: '2024-05-10',
    metrics: [
      {
        id: 'dad-w',
        name: '体重',
        category: '基础体态',
        value: 78.0,
        unit: 'kg',
        normalRange: '60.0 ~ 71.0',
        status: 'attention',
        meaning: '明显超重（超标约 7 公斤），腰围负荷大',
        advice: '腹部脂肪是血压和血脂升高的主因，目标循序渐进减重 5 斤。',
        trend: 'up',
      },
      {
        id: 'dad-bmi',
        name: '体质指数 (BMI)',
        category: '基础体态',
        value: 26.4,
        unit: 'kg/m²',
        normalRange: '18.5 ~ 23.9',
        status: 'attention',
        meaning: '超重状态（属于轻度向肥胖靠近）',
        advice: '少吃红烧肉、肥肉和油炸花生米，多吃芹菜木耳等富含纤维蔬菜。',
        trend: 'up',
      },
      {
        id: 'dad-bp-sys',
        name: '收缩压 (高压)',
        category: '心血管与血压',
        value: 136,
        unit: 'mmHg',
        normalRange: '90 ~ 130',
        status: 'attention',
        meaning: '偏高！晨起容易超过 135，属于需要重点干预的临界高血压',
        advice: '必须每日打卡，严格控盐，早晨起床动作放慢，先坐 2 分钟再站立。',
        trend: 'up',
      },
      {
        id: 'dad-bp-dia',
        name: '舒张压 (低压)',
        category: '心血管与血压',
        value: 86,
        unit: 'mmHg',
        normalRange: '60 ~ 85',
        status: 'attention',
        meaning: '处于临界偏高状态，说明外周血管阻力增加',
        advice: '戒烟限酒，情绪保持平稳放松，睡前避免刷手机兴奋。',
        trend: 'stable',
      },
      {
        id: 'dad-glu',
        name: '空腹血糖',
        category: '血糖代谢',
        value: 6.2,
        unit: 'mmol/L',
        normalRange: '3.9 ~ 6.1',
        status: 'attention',
        meaning: '稍偏高（空腹血糖受损临界）',
        advice: '主食把白米饭的 1/3 换成燕麦、糙米或杂粮窝头，饭后不要立刻躺卧。',
        trend: 'up',
      },
      {
        id: 'dad-hba1c',
        name: '糖化血红蛋白',
        category: '血糖代谢',
        value: 5.9,
        unit: '%',
        normalRange: '4.0 ~ 6.0',
        status: 'normal',
        meaning: '尚在安全界限内，但已逼近 6.0% 的临界线',
        advice: '严格管住零食甜食，每 3 个月监测一次。',
        trend: 'up',
      },
      {
        id: 'dad-tc',
        name: '总胆固醇 (TC)',
        category: '血脂四项',
        value: 5.10,
        unit: 'mmol/L',
        normalRange: '2.80 ~ 5.18',
        status: 'normal',
        meaning: '在参考标准上限，需预防上升',
        advice: '每周吃蛋黄控制在 4 个以内，少吃动物油。',
        trend: 'stable',
      },
      {
        id: 'dad-tg',
        name: '甘油三酯 (TG)',
        category: '血脂四项',
        value: 2.35,
        unit: 'mmol/L',
        normalRange: '0.56 ~ 1.70',
        status: 'danger',
        meaning: '明显偏高！提示血液油脂过多，多与饮酒、高脂饮食有关',
        advice: '重点关注项：坚决少吃高油脂食物，不饮烈酒，饭后坚持活动。',
        trend: 'up',
      },
      {
        id: 'dad-ldl',
        name: '低密度脂蛋白 (LDL-C)',
        category: '血脂四项',
        value: 2.85,
        unit: 'mmol/L',
        normalRange: '< 2.60',
        status: 'attention',
        meaning: '轻度偏高，需防止在血管壁沉积造成动脉硬化',
        advice: '多吃洋葱、黑木耳、深海鱼，配合日常适度锻炼。',
        trend: 'stable',
      },
      {
        id: 'dad-hdl',
        name: '高密度脂蛋白 (HDL-C)',
        category: '血脂四项',
        value: 1.08,
        unit: 'mmol/L',
        normalRange: '> 1.04',
        status: 'normal',
        meaning: '基本达标',
        advice: '戒烟与慢跑/快走是提升该指标的最佳天然方法。',
        trend: 'stable',
      },
      {
        id: 'dad-ua',
        name: '血尿酸 (UA)',
        category: '肝肾与痛风',
        value: 445,
        unit: 'μmol/L',
        normalRange: '208 ~ 428',
        status: 'danger',
        meaning: '偏高！高尿酸血症，极易诱发大脚趾或关节痛风红肿发作',
        advice: '重点关注项：坚决不喝老火浓肉汤、海鲜火锅汤，不喝啤酒，多喝白开水促排泄。',
        trend: 'up',
      },
      {
        id: 'dad-hr',
        name: '静息心率',
        category: '心血管与血压',
        value: 74,
        unit: '次/分',
        normalRange: '60 ~ 100',
        status: 'normal',
        meaning: '心跳节律整齐平稳',
        advice: '血压测量时同时关注心率，超过 85 时多坐下深呼吸。',
        trend: 'stable',
      },
    ],
    visitGuide: {
      recommendedDept: '心血管内科门诊 / 内分泌科门诊',
      reason: '晨起收缩压波动（135左右）、甘油三酯偏高（2.35）、血尿酸偏高（445），属于典型代谢综合征状态，需优化降压控脂方案。',
      checklist: [
        '医保卡 & 身份证件',
        '手机中近 1 个月的早晚血压打卡日志（或手写记录本）',
        '当前正在吃的所有降压药盒（让医生看具体成分与毫克数）',
        '最近一次生化体检单（主要看尿酸、肾功能与甘油三酯）',
      ],
      questionsToDoctor: [
        '1. “医生，我早晨测的血压经常在 135-140 mmHg，目前吃的降压药是否需要调整剂量，或者换在早晨刚起床时吃？”',
        '2. “我的血尿酸有 445、甘油三酯 2.35，我现在吃的降压药里面有没有利尿剂成分？利尿剂会不会影响尿酸排泄？”',
        '3. “请问我的情况需要做一个 24 小时动态血压监测或者心脏彩超吗？”',
      ],
      lifestyleAdvice: [
        '极重要：低盐饮食！每天盐摄入严格限制在一啤酒瓶盖（5克）以内，少蘸酱油少吃咸菜。',
        '勤喝温开水：每天分多次喝足 1500~2000ml，多排尿是降低尿酸最安全有效的自然疗法。',
        '管住嘴戒浓汤：拒绝熬了几个小时的老火骨头汤、肉汤、荤油火锅，嘌呤极高伤肾伤关节。',
      ],
      nextReviewDate: '2024-11-15 (建议 3 个月复查血压与生化指标)',
    },
  },
};
