import { MemberHealthProfile } from '@/types/health';

export const PARENT_HEALTH_PROFILES: Record<string, MemberHealthProfile> = {
  mom: {
    memberId: 'mom',
    memberName: '妈妈 (周芸)',
    lastExamDate: '2026-07-29',
    metrics: [
      {
        id: 'mom-moca',
        name: 'MoCA 认知量表评分',
        category: '专科特检',
        value: 17,
        unit: '分/满分30',
        normalRange: '≥ 26',
        status: 'attention',
        meaning: '结合 12 年中专受教育年限评估，提示存在轻度认知功能下降',
        advice: '积极进行脑力锻炼与社交互动，遵医嘱规范服用多奈哌齐，定期复查量表。',
        trend: 'stable',
      },
      {
        id: 'mom-mmse',
        name: 'MMSE 简易智力量表',
        category: '专科特检',
        value: 29,
        unit: '分/满分30',
        normalRange: '≥ 27',
        status: 'normal',
        meaning: 'MMSE 得分处于正常认知界限内，定向力与语言理解能力良好',
        advice: '日常生活自理能力完好，保持良好生活心态。',
        trend: 'stable',
      },
      {
        id: 'mom-psg-ahi',
        name: 'PSG 原始呼吸暂停指数 (未戴机)',
        category: '专科特检',
        value: 70.7,
        unit: '次/小时',
        normalRange: '< 5.0',
        status: 'danger',
        meaning: '睡眠多导监测确诊重度阻塞性睡眠呼吸暂停 (OSAHS)',
        advice: '必须每夜规律佩戴 CPAP 呼吸机治疗，纠正夜间缺氧，保护脑白质与心脑血管。',
        trend: 'down',
      },
      {
        id: 'mom-psg-spo2',
        name: 'PSG 最低夜间血氧 (未戴机)',
        category: '专科特检',
        value: 79,
        unit: '%',
        normalRange: '≥ 90',
        status: 'danger',
        meaning: '未佩戴呼吸机时夜间出现严重低氧血症 (ODI 43.7/h)',
        advice: '佩戴 CPAP 治疗后血氧维持在正常 95% 以上，必须持之以恒。',
        trend: 'up',
      },
      {
        id: 'mom-cpap-ahi',
        name: 'CPAP 呼吸机治疗后 AHI',
        category: '专科特检',
        value: 1.2,
        unit: '次/小时',
        normalRange: '< 5.0',
        status: 'normal',
        meaning: '治疗效果极其显著！戴机后整夜无缺氧憋气，AHI 长期稳定在 1~2 次/小时',
        advice: '维持 ResMed AutoSet 治疗压力，注意面罩清洁与密封调谐。',
        trend: 'down',
      },
      {
        id: 'mom-fazekas',
        name: '脑白质高信号 (Fazekas分级)',
        category: '专科特检',
        value: '1级',
        unit: '分级',
        normalRange: '0 ~ 1级',
        status: 'attention',
        meaning: '头颅 MRI 见双侧皮层下斑点样白质高信号（提示年龄相关退行性改变，未诊断CSVD）',
        advice: '严格控制血压血脂、坚持呼吸机纠正缺氧是遏制白质进展的核心。',
        trend: 'stable',
      },
      {
        id: 'mom-bp-sys',
        name: '收缩压 (高压)',
        category: '心血管与血压',
        value: 126,
        unit: 'mmHg',
        normalRange: '90 ~ 130',
        status: 'normal',
        meaning: '指标非常理想，血管张力稳定',
        advice: '继续保持平稳心态与规律作息。',
        trend: 'stable',
      },
      {
        id: 'mom-bp-dia',
        name: '舒张压 (低压)',
        category: '心血管与血压',
        value: 78,
        unit: 'mmHg',
        normalRange: '60 ~ 85',
        status: 'normal',
        meaning: '处于黄金健康范围',
        advice: '早晚测量如无明显波动即十分安全。',
        trend: 'stable',
      },
      {
        id: 'mom-hba1c',
        name: '糖化血红蛋白 (HbA1c)',
        category: '血糖代谢',
        value: 5.4,
        unit: '%',
        normalRange: '4.0 ~ 6.0',
        status: 'normal',
        meaning: '近3个月综合血糖控制非常优秀',
        advice: '继续保持良好的清淡杂粮膳食结构。',
        trend: 'stable',
      },
      {
        id: 'mom-ldl',
        name: '低密度脂蛋白 (LDL-C)',
        category: '血脂四项',
        value: 2.84,
        unit: 'mmol/L',
        normalRange: '< 2.60',
        status: 'attention',
        meaning: '轻度偏高，属于血管动脉粥样硬化防范关注指标',
        advice: '低脂清淡饮食，减少动物油脂摄入，定期随访血管超声。',
        trend: 'stable',
      },
      {
        id: 'mom-apoe',
        name: 'APOE 基因分型',
        category: '专科特检',
        value: 'ε2/ε3',
        unit: '型别',
        normalRange: 'ε3/ε3为常见型',
        status: 'normal',
        meaning: '非高风险 ε4 基因携带者，遗传风险背景相对温和',
        advice: '定期临床随访，维持良好生活方式。',
        trend: 'stable',
      },
      {
        id: 'mom-ptau',
        name: '阿尔茨海默病标志物 (p-tau181/217)',
        category: '专科特检',
        value: '正常未见异常',
        unit: '定性',
        normalRange: '阴性/正常',
        status: 'normal',
        meaning: '血液高敏标志物未提示典型阿尔茨海默病改变（不能单独替代临床全面评估）',
        advice: '仁济病历未诊断 AD，遵从耿医生建议综合调理认知。',
        trend: 'stable',
      },
    ],
    visitGuide: {
      recommendedDept: '上海仁济医院 神经内科（耿介立医生团队）/ 睡眠医学中心',
      reason: '遗忘与认知功能评估随访；复查 EEG 脑电图；确认头颅 CTA 与 SWI 检查安排；睡眠呼吸机长期疗效监测。',
      checklist: [
        '医保卡 & 上海仁济医院就医凭证',
        '2026-07-29 仁济门诊病历原件',
        '头颅 MRI 影像片与报告单（重点向医生核对眼动脉根部小突起与白质高信号）',
        '手机中近 1 个月的 CPAP 呼吸机每日使用时长与 AHI 曲线',
        '目前服用的所有药盒：多奈哌齐（5mg）、胞磷胆碱钠（宝诺达）',
        '晨起与睡前静息心率打卡记录单（确保心率>55次/分）',
      ],
      questionsToDoctor: [
        '1. “耿医生您好，上次病历中我母亲的受教育年限误录成了2年，实际她是中专毕业受教育12年，请您在随访系统里帮我们更正一下。”',
        '2. “目前母亲每天晚上固定服用多奈哌齐 5mg，我们每天测心率都在 60~72 次/分（始终在55次以上），适应良好，请问需要按计划开具复查脑电图 EEG 和头颅 CTA 吗？”',
        '3. “母亲坚持使用呼吸机后，AHI 基本控制在 1~2 之间，精神状态改善。一般建议戴机多长时间后复评一次 MoCA 认知量表？”',
        '4. “针对眼动脉根部的小突起，后续需要做 CTA 进一步明确吗？”',
      ],
      lifestyleAdvice: [
        '按医嘱每晚服用多奈哌齐 5mg，如晨起心率低于 55 次/分应暂停并咨询医生。',
        '持续每晚佩戴 CPAP 呼吸机，保持面罩边缘密封，防止漏气吹向眼睛。',
        '积极开展脑力锻炼与日常社交：多读书报、练习手指操、记账算题、与家人朋友交谈。',
        '坚持每日傍晚快走散步 30 分钟，持之以恒，有助促进脑部血液循环与情绪愉悦。',
      ],
      nextReviewDate: '2026-10-29 (建议 3 个月复查认知与睡眠评估)',
    },
  },
  dad: {
    memberId: 'dad',
    memberName: '爸爸 (李永群)',
    lastExamDate: '2026-07-13',
    metrics: [
      {
        id: 'dad-hgb',
        name: '血红蛋白 (HGB)',
        category: '专科特检',
        value: 122,
        unit: 'g/L',
        normalRange: '120 ~ 160',
        status: 'normal',
        meaning: '胃 ESD 术后贫血已稳步恢复至正常低线 (120~122 g/L 稳定段)',
        advice: '铁蛋白已充足 (345)，切勿盲目自行口服铁剂，均衡摄入鱼肉蛋禽即可。',
        trend: 'up',
      },
      {
        id: 'dad-cr',
        name: '血肌酐 (Cr)',
        category: '肝肾与痛风',
        value: 106.97,
        unit: 'μmol/L',
        normalRange: '57.0 ~ 111.0',
        status: 'normal',
        meaning: '肌酐已完全恢复至正常参考范围内！肾内科医生评估“没有肾病了”',
        advice: '日常多喝温开水，保持每日尿量充足，定期复查肾功能。',
        trend: 'down',
      },
      {
        id: 'dad-ca724',
        name: '胃肿瘤标志物 CA72-4',
        category: '专科特检',
        value: 9.02,
        unit: 'U/mL',
        normalRange: '< 10.0',
        status: 'normal',
        meaning: '极佳转归！由术前 31.4 U/mL 显著回落至正常安全值 9.02 U/mL',
        advice: '提示胃 ESD 病灶切除彻底，按医嘱定期进行常规胃镜随访。',
        trend: 'down',
      },
      {
        id: 'dad-bp-sys',
        name: '收缩压 (高压)',
        category: '心血管与血压',
        value: 128,
        unit: 'mmHg',
        normalRange: '90 ~ 130',
        status: 'normal',
        meaning: '非洛地平规律服药下，晨起血压稳定达标',
        advice: '坚持早餐后服用非洛地平 5mg，严格控制烹饪食盐摄入。',
        trend: 'stable',
      },
      {
        id: 'dad-bp-dia',
        name: '舒张压 (低压)',
        category: '心血管与血压',
        value: 82,
        unit: 'mmHg',
        normalRange: '60 ~ 85',
        status: 'normal',
        meaning: '外周血管阻力处于平稳受控状态',
        advice: '情绪放松，规律作息，避免猛烈起坐。',
        trend: 'stable',
      },
      {
        id: 'dad-hba1c',
        name: '糖化血红蛋白 (HbA1c)',
        category: '血糖代谢',
        value: 5.7,
        unit: '%',
        normalRange: '4.0 ~ 5.6',
        status: 'attention',
        meaning: '处于临界高值边缘（5.7%），提示需预防胰岛素抵抗',
        advice: '主食粗细搭配，少吃稀饭烂面与甜食，餐后适度散步活动。',
        trend: 'up',
      },
      {
        id: 'dad-ldl',
        name: '低密度脂蛋白 (LDL-C)',
        category: '血脂四项',
        value: 3.21,
        unit: 'mmol/L',
        normalRange: '< 2.60',
        status: 'attention',
        meaning: '轻度偏高，伴冠脉及主动脉钙化，需心内科综合评估调脂',
        advice: '减少高胆固醇与油腻荤油食物，适度增加富含膳食纤维蔬菜。',
        trend: 'up',
      },
      {
        id: 'dad-acr',
        name: '尿微量白蛋白/肌酐比 (ACR)',
        category: '肝肾与痛风',
        value: 28.52,
        unit: 'mg/g',
        normalRange: '< 30.0',
        status: 'normal',
        meaning: '尿蛋白阴性，ACR 处于正常安全范围，无糖尿病或高血压肾损害征象',
        advice: '继续平稳控制血压即可有效保护肾血管。',
        trend: 'stable',
      },
      {
        id: 'dad-emg',
        name: '肌电图正中神经卡压',
        category: '专科特检',
        value: '双侧腕部卡压可能',
        unit: '评估',
        normalRange: '正常传导',
        status: 'attention',
        meaning: '双侧正中神经传导速度减慢（腕管综合征方向），手部偶尔麻木',
        advice: '避免手腕过度用力与长期曲折，夜间建议佩戴中立位护腕，口服甲钴胺。',
        trend: 'stable',
      },
      {
        id: 'dad-cervical',
        name: '颈椎 MRI (多节段膨出)',
        category: '专科特检',
        value: 'C3/4-C6/7突出',
        unit: '分段',
        normalRange: '未见突出',
        status: 'attention',
        meaning: '多节段局限性突出伴椎管狭窄、C5/6终板炎可能',
        advice: '严禁重手法推拿或快速暴力扳头！使用高度合适护颈枕。',
        trend: 'stable',
      },
      {
        id: 'dad-stomach-status',
        name: '胃 ESD 术后状态',
        category: '专科特检',
        value: '已治愈 / 常规随访',
        unit: '状态',
        normalRange: '治愈',
        status: 'normal',
        meaning: '仁济主治医师明确告知治愈、无需追加化疗或手术处理',
        advice: '按医嘱口服替普瑞酮、胃复春保护胃黏膜，定期随访胃镜。',
        trend: 'stable',
      },
    ],
    visitGuide: {
      recommendedDept: '上海仁济医院 消化内科（ESD随访）/ 心血管内科门诊',
      reason: '早期胃癌胃 ESD 术后定期常规胃镜复查；高血压与血脂（LDL-C 3.21）长期规范管理；腕管综合征随访。',
      checklist: [
        '医保卡 & 仁济医院就诊磁卡',
        '2026-05 仁济胃 ESD 手术病理切片与出院小结原件',
        '2026-07-13 贵医附院血常规、肾功能、尿检与超声化验单',
        '近 1 个月家庭血压打卡记录手册（高压/低压/心率）',
        '目前服用的所有药物：非洛地平（5mg）、甲钴胺（0.5mg）、替普瑞酮、胃复春',
      ],
      questionsToDoctor: [
        '1. “医生您好，我5月份在仁济做了早期胃癌胃 ESD，主治医师告知已经治愈。请问下一次常规随访胃镜安排在术后半年还是一年？”',
        '2. “我7月份复查血常规 HGB 已经恢复到 122 g/L，肌酐 106.97 正常，CA72-4 降到了 9.02。替普瑞酮和胃复春还需要继续吃多久？”',
        '3. “我的低密度脂蛋白（LDL-C）是 3.21，体检有主动脉和冠脉钙化，平时一直在吃非洛地平降压，请问需要加小剂量他汀降脂防斑块吗？”',
        '4. “仁济肌电图提示有双侧正中神经腕部卡压（腕管综合征），平时手偶尔发麻，除了吃甲钴胺，晚上戴护腕固定有效吗？”',
      ],
      lifestyleAdvice: [
        '严格低盐饮食：每天用盐控制在 5 克以内（约一个啤酒瓶盖量），坚决少吃或不吃腌咸菜、酱腐乳。',
        '胃黏膜保护养生：三餐定时定量，细嚼慢咽，饭后半小时不剧烈运动或直接卧床，忌生冷刺激与高浓咖啡茶。',
        '保护颈椎与手腕：避免长时间低头刷手机或手腕屈曲干重活；睡眠时选择符合颈椎生理曲度的枕头；严禁暴力扳弄颈椎。',
        '温开水多次补充：每日分次饮用温开水 1500~1800 ml，促进新陈代谢。',
      ],
      nextReviewDate: '2026-11-15 (建议术后半年常规复诊)',
    },
  },
};
